# Github
name: issue-greeter
on: "push"
jobs:
  notify-devpanel:
    runs-on: ubuntu-latest
    steps:
      - name: notify
        run: |
          curl -s -X PUT https://test.site.devpanel.com/web-hooks/multistack/webhooks/62068113b5f85500153f9393/applications/62068115b5f85500153f9399 \
            -d '{}'
            -H "Authorization: Bearer ${{ secrets.DP_TOKEN }}" \
